def main():
  print('When day comes, we ask ourselves, where can we find light in this never-ending shade?')
  print('')
  print('The loss we carry. A sea we must wade.')
  print('We braved the belly of the beast.')
  print('')
  print("We've learned that quiet isn't always peace,")
  print('and the norms and notions of what "just" is ', end="")
  print("isn't always justice.", end="\n")
  print('')
  print('And yet the dawn is ours before we knew it.')
  print('')
  print('Somehow we do it.')
main()